EXAMPLES_API.md, EXAMPLES_CLI.md, README.md, bin.js, package-lock.json, package.json, src/bin.ts, src/commands/cert.ts, src/commands/wallet.ts, src/index.ts, src/wallet/index.ts, src/wallet/storage.ts, test.html, webpack.config.js, yarn.lock
adds support for generating and storing wallets, add support for using with CLI (min-cli, no dips), adds some examples.
=> [feat] bin,wallet,keytar, add examples

.github/workflows/npm.yml, package-lock.json, package.json
introduces changelog for creating releases.
use #major , #minor, or any merge into main will generate and publish a #minor
=> cleanup cicd delivery

.gitignore, package.json, src/deployments/index.ts, src/index.ts, src/network/index.ts, src/stargate/index.ts, src/wallet/index.ts, yarn.lock
Add function to pull network metadata and return the API endpoints for rest or rpc
=> add functions to get network endpoints

package.json
Add the generated JS files to the NPM package.
=> Add generated js files to npm package

src/webpack/perf_hooks.ts, webpack.config.js
Fixes the webpack build by aliasing pref_hooks to browser implementation.
=> Fix webpack build

src/certificates/generate509.ts
* Small formatting nit from linter :-|
* Changes validity period from 2 years, to 1. 
* Changes authentication extension from `serverAuth` to `clientAuth`
=> updates cert gen ext

package.json, src/keplr/index.ts, src/pbclient/index.ts, src/stargate/index.ts, yarn.lock
this PR addresses ovrclk/engineering#274 to move over to an amino compatible client, or providing the proto client for non ledger accounts. 
There is one amino message registered, but it is not working just yet.
=> gets the amino signer if needed from keplr

examples/README.md, examples/get_deployments.ts, src/rpc/index.ts
Updates the documentation to reflect the change to getRpc's call signature
=> update examples to reflect change in getRpc signature

package.json, src/rpc/index.ts, tsconfig.json, yarn.lock
Adds a utility for creating a signing message client using an offline signer (ie: keplr).
=> Add utility method for creating signed message client

src/protobuf/cosmos/base/v1beta1/coin.ts
Fix the encoder for deccoin to prevent the value from being reduced.
=> fix encode for deccoin

package.json, src/sdl/index.ts, tests/test_sdl_sweeper.ts
Add support for toggling some values resulting in an invalid group config.
=> Fix issue with invalid groups output

src/sdl/index.ts, src/sdl/sizes.ts, src/sdl/types.ts
Adds support for specifying vendor/models as GPU attributes in SDLs.
=> feat: add support for gpu attributes

src/sdl/index.ts, tests/test_sdl_gpu.ts, tests/test_sdl_gpu_vendor_only.ts
Fixes an exception when the vendor is specific, but without any models.
=> fix: missing tests and vendor-only gpu spec

src/sdl/index.ts, tap-snapshots/tests/test_sdl_gpu_vendor_only.ts.test.cjs, tests/test_sdl_gpu_vendor_only.ts
Fixes the specification of vendor-only GPU requirements to append wildcard.
=> fix: vendor-only models using wildcard

package.json, src/sdl/index.ts, src/sdl/types.ts, tap-snapshots/tests/test_sdl_ip_lease.ts.test.cjs, tap-snapshots/tests/test_sdl_persistent_storage_attributes.ts.test.cjs, tests/fixtures/ip_lease_valid.sdl.yml, tests/fixtures/persistent_storage_valid.sdl.yml, tests/test_sdl_ip_lease.ts, tests/test_sdl_persistent_storage_attributes.ts, yarn.lock
- Switched to using [rimraf](https://github.com/isaacs/rimraf) in node scripts instead of `rm -rf` for cross-platform compatibility
- Fixed issue when using IP Lease feature
- Fixed resource attributes encoding (fixes #42 with similar changes as in #43 )
- Fixed issue when using multi-service deployments
=> Fix ip lease and persistent storage

src/sdl/index.ts, src/sdl/types.ts, tap-snapshots/tests/test_sdl_v3_resources.ts.test.cjs, tap-snapshots/tests/test_sdl_wordpress.ts.test.cjs, tests/test_sdl_basic.ts, tests/test_sdl_basic_beta3.ts, tests/test_sdl_empty_profile.ts, tests/test_sdl_sweeper.ts
Change signedBy naming to match protobuf types
`signed_by` => `signedBy`
`all_off` => `allOf`
`any_off` => `anyOf`
=> Fix signedby attributes

src/stargate/index.ts
=> chore: update the messages type for beta3

.vscode/launch.json, examples/create_deployment.ts, src/certificates/index.ts, src/pbclient/index.ts
Adds an example for a full deployment flow to the examples directory
=> feat: add example for full deployment

src/sdl/SDL/SDL.spec.ts, src/sdl/SDL/SDL.ts
refs akash-network/cloudmos#133
=> fix(sdl): fallback credentials email to an empty string

examples/get_lease_status.ts
=> chore(examples): update get_lease_status.ts example

examples/create_deployment.ts, package-lock.json, package.json, src/pbclient/pbclient.spec.ts, src/pbclient/pbclient.ts, src/rpc/index.ts
- Updated cosmjs packages to latest version
- Remove old cosmwasm package in favor of cosmjs
=> fix: update deps

package-lock.json, package.json
=> chore: update package.json to add lodash dependency

package-lock.json, package.json, tap-snapshots/tests/test_deployments.ts.test.cjs
1. axios -> https://github.com/advisories/GHSA-jr5f-v2jv-69x6
2. @cosmos/launchpad uses old axios version  and actually deprecated-> https://github.com/chainapsis/keplr-wallet/issues/521?utm_source=chatgpt.com
=> fix: updates deps
